_wandb:
    value:
        cli_version: 0.23.0
        e:
            pqontxluqq7z9u8fu5siigr7637w9ekx:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "2147483648"
                codePath: example_run.py
                codePathLocal: example_run.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "377953218560"
                email: suyashtripathi82@gmail.com
                executable: /Users/sam/Watson/.venv/bin/python3
                git:
                    commit: 1c2d0e24a9141fe7a90670282d8b7a0129099013
                    remote: https://github.com/samx3499/Watson
                host: Sams-Laptop.local
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/sam/Watson/example_run.py
                python: CPython 3.13.5
                root: /Users/sam/Watson
                startedAt: "2025-11-22T01:52:29.395377Z"
                writerId: pqontxluqq7z9u8fu5siigr7637w9ekx
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 95
            "2":
                - 95
            "3":
                - 16
            "4": 3.13.5
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
agent_model:
    value: openai/gpt-4o-mini
environment_model:
    value: openai/gpt-4o-mini
reward_model:
    value: openai/gpt-4o-mini
